language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - 7.0

matrix:
  allow_failures:
    - php: 7.0

install:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit -c travis.phpunit.xml
